version: '3.3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app/target
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
